name: Go Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' 

      - name: Run golangci-lint (install & run)
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: run ./...
